//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNancy.Rules.RuleSet.DataAccess.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class RuleDefinition
    {
        
        private string _ruleName;
        
        private System.Xml.XmlDocument _definition;
        
        private bool _paused;
        
        private System.DateTime _dateCreated;
        
        private System.Guid _createdBy;
        
        private bool _deleted;
        
        private System.DateTime _dateUpdated;
        
        private System.Guid _updatedBy;
        
        private System.Guid _ruleID;
        
        private System.Guid _typeID;
        
        private System.Guid _applicationID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public RuleDefinition()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        public virtual string RuleName
        {
            get
            {
                return this._ruleName;
            }
            set
            {
                this._ruleName = value;
                this.SetIsModified("RuleName");
            }
        }
        
        public virtual System.Xml.XmlDocument Definition
        {
            get
            {
                return this._definition;
            }
            set
            {
                this._definition = value;
                this.SetIsModified("Definition");
            }
        }
        
        public virtual bool Paused
        {
            get
            {
                return this._paused;
            }
            set
            {
                this._paused = value;
                this.SetIsModified("Paused");
            }
        }
        
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._dateCreated;
            }
            set
            {
                this._dateCreated = value;
                this.SetIsModified("DateCreated");
            }
        }
        
        public virtual System.Guid CreatedBy
        {
            get
            {
                return this._createdBy;
            }
            set
            {
                this._createdBy = value;
                this.SetIsModified("CreatedBy");
            }
        }
        
        public virtual bool Deleted
        {
            get
            {
                return this._deleted;
            }
            set
            {
                this._deleted = value;
                this.SetIsModified("Deleted");
            }
        }
        
        public virtual System.DateTime DateUpdated
        {
            get
            {
                return this._dateUpdated;
            }
            set
            {
                this._dateUpdated = value;
                this.SetIsModified("DateUpdated");
            }
        }
        
        public virtual System.Guid UpdatedBy
        {
            get
            {
                return this._updatedBy;
            }
            set
            {
                this._updatedBy = value;
                this.SetIsModified("UpdatedBy");
            }
        }
        
        public virtual System.Guid RuleID
        {
            get
            {
                return this._ruleID;
            }
            set
            {
                this._ruleID = value;
                this.SetIsModified("RuleID");
            }
        }
        
        public virtual System.Guid TypeID
        {
            get
            {
                return this._typeID;
            }
            set
            {
                this._typeID = value;
                this.SetIsModified("TypeID");
            }
        }
        
        public virtual System.Guid ApplicationID
        {
            get
            {
                return this._applicationID;
            }
            set
            {
                this._applicationID = value;
                this.SetIsModified("ApplicationID");
            }
        }       
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("RuleName", false);
            this.IsModifiedDictionary.Add("Definition", false);
            this.IsModifiedDictionary.Add("Paused", false);
            this.IsModifiedDictionary.Add("DateCreated", false);
            this.IsModifiedDictionary.Add("CreatedBy", false);
            this.IsModifiedDictionary.Add("Deleted", false);
            this.IsModifiedDictionary.Add("DateUpdated", false);
            this.IsModifiedDictionary.Add("UpdatedBy", false);
            this.IsModifiedDictionary.Add("RuleID", false);
            this.IsModifiedDictionary.Add("TypeID", false);
            this.IsModifiedDictionary.Add("ApplicationID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
