//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNancy.Rules.RuleSet.DataAccess.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class RuleStatistic
    {
        
        private string _ruleName;
        
        private System.Guid _referenceID;
        
        private bool _result;
        
        private System.Guid _ruleStatisticID;
        
        private System.Guid _applicationID;
        
        private System.Guid _typeID;
        
        private System.Guid _ruleID;
        
        private System.DateTime _dateInserted;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public RuleStatistic()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        public virtual string RuleName
        {
            get
            {
                return this._ruleName;
            }
            set
            {
                this._ruleName = value;
                this.SetIsModified("RuleName");
            }
        }
        
        public virtual System.Guid ReferenceID
        {
            get
            {
                return this._referenceID;
            }
            set
            {
                this._referenceID = value;
                this.SetIsModified("ReferenceID");
            }
        }
        
        public virtual bool Result
        {
            get
            {
                return this._result;
            }
            set
            {
                this._result = value;
                this.SetIsModified("Result");
            }
        }
        
        public virtual System.Guid RuleStatisticID
        {
            get
            {
                return this._ruleStatisticID;
            }
            set
            {
                this._ruleStatisticID = value;
                this.SetIsModified("RuleStatisticID");
            }
        }
        
        public virtual System.Guid ApplicationID
        {
            get
            {
                return this._applicationID;
            }
            set
            {
                this._applicationID = value;
                this.SetIsModified("ApplicationID");
            }
        }
        
        public virtual System.Guid TypeID
        {
            get
            {
                return this._typeID;
            }
            set
            {
                this._typeID = value;
                this.SetIsModified("TypeID");
            }
        }
        
        public virtual System.Guid RuleID
        {
            get
            {
                return this._ruleID;
            }
            set
            {
                this._ruleID = value;
                this.SetIsModified("RuleID");
            }
        }
        
        public virtual System.DateTime DateInserted
        {
            get
            {
                return this._dateInserted;
            }
            set
            {
                this._dateInserted = value;
                this.SetIsModified("DateInserted");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("RuleName", false);
            this.IsModifiedDictionary.Add("ReferenceID", false);
            this.IsModifiedDictionary.Add("Result", false);
            this.IsModifiedDictionary.Add("RuleStatisticID", false);
            this.IsModifiedDictionary.Add("ApplicationID", false);
            this.IsModifiedDictionary.Add("TypeID", false);
            this.IsModifiedDictionary.Add("RuleID", false);
            this.IsModifiedDictionary.Add("DateInserted", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
