//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNancy.Rules.RuleSet.DataAccess.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class UserStore
    {
        
        private string _firstName;
        
        private string _lastName;
        
        private string _email;
        
        private string _password;
        
        private System.DateTime _lastLogin;
        
        private System.DateTime _dateCreated;
        
        private System.Guid _createdBy;
        
        private bool _isSuperUser;
        
        private System.Guid _userID;
        
        private Dictionary<string, bool> _isModifiedDictionary = new Dictionary<string, bool>();
        
        public UserStore()
        {
            this.InitializeIsModifiedDictionary();
        }
        
        public virtual string FirstName
        {
            get
            {
                return this._firstName;
            }
            set
            {
                this._firstName = value;
                this.SetIsModified("FirstName");
            }
        }
        
        public virtual string LastName
        {
            get
            {
                return this._lastName;
            }
            set
            {
                this._lastName = value;
                this.SetIsModified("LastName");
            }
        }
        
        public virtual string Email
        {
            get
            {
                return this._email;
            }
            set
            {
                this._email = value;
                this.SetIsModified("Email");
            }
        }
        
        public virtual string Password
        {
            get
            {
                return this._password;
            }
            set
            {
                this._password = value;
                this.SetIsModified("Password");
            }
        }
        
        public virtual System.DateTime LastLogin
        {
            get
            {
                return this._lastLogin;
            }
            set
            {
                this._lastLogin = value;
                this.SetIsModified("LastLogin");
            }
        }
        
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._dateCreated;
            }
            set
            {
                this._dateCreated = value;
                this.SetIsModified("DateCreated");
            }
        }
        
        public virtual System.Guid CreatedBy
        {
            get
            {
                return this._createdBy;
            }
            set
            {
                this._createdBy = value;
                this.SetIsModified("CreatedBy");
            }
        }
        
        public virtual bool IsSuperUser
        {
            get
            {
                return this._isSuperUser;
            }
            set
            {
                this._isSuperUser = value;
                this.SetIsModified("IsSuperUser");
            }
        }
        
        public virtual System.Guid UserID
        {
            get
            {
                return this._userID;
            }
            set
            {
                this._userID = value;
                this.SetIsModified("UserID");
            }
        }
        
        public virtual Dictionary<string, bool> IsModifiedDictionary
        {
            get
            {
                return this._isModifiedDictionary;
            }
            set
            {
                this._isModifiedDictionary = value;
            }
        }
        
        private void InitializeIsModifiedDictionary()
        {
            this.IsModifiedDictionary.Add("FirstName", false);
            this.IsModifiedDictionary.Add("LastName", false);
            this.IsModifiedDictionary.Add("Email", false);
            this.IsModifiedDictionary.Add("Password", false);
            this.IsModifiedDictionary.Add("LastLogin", false);
            this.IsModifiedDictionary.Add("DateCreated", false);
            this.IsModifiedDictionary.Add("CreatedBy", false);
            this.IsModifiedDictionary.Add("IsSuperUser", false);
            this.IsModifiedDictionary.Add("UserID", false);
        }
        
        private void SetIsModified(string columnName)
        {
            if ((this.IsModifiedDictionary.ContainsKey(columnName) == true))
            {
                IsModifiedDictionary[columnName] = true;
            }
        }
    }
}
