//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNancy.Rules.RuleSet.DataAccess.DTO.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;


    public class Application_User : List<DTO.Application_User>
    {
        
        private CustomDatabaseHelper _baseDatabase = new CustomDatabaseHelper();
        
        public Application_User(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Application_User()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {

            DTO.Application_User dto;
                using(reader)
                {

                while(reader.Read())
                {
                    dto = new DTO.Application_User();
                    dto.ApplicationID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("ApplicationID"), reader);
                    dto.UserID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("UserID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
