//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNancy.Rules.RuleSet.DataAccess.DTO.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    
    
    public class ConfigurationFile : List<DotNetNancy.Rules.RuleSet.DataAccess.DTO.ConfigurationFile>
    {
        
       CustomDatabaseHelper _baseDatabase = new CustomDatabaseHelper();
        
        public ConfigurationFile(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public ConfigurationFile()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            DotNetNancy.Rules.RuleSet.DataAccess.DTO.ConfigurationFile dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new DotNetNancy.Rules.RuleSet.DataAccess.DTO.ConfigurationFile();
            dto.ConfigurationFile_Property = new System.Xml.XmlDocument();
                    dto.ConfigurationFile_Property.Load(reader.GetSqlXml(reader.GetOrdinal("ConfigurationFile")).CreateReader());
                    dto.TypeID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("TypeID"), reader);
                    dto.ApplicationID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("ApplicationID"), reader);
                    dto.ConfigurationTypeID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("ConfigurationTypeID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
