//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNancy.Rules.RuleSet.DataAccess.DTO.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;


    public class ConfigurationType : List<DTO.ConfigurationType>
    {
        
        private CustomDatabaseHelper _baseDatabase = new CustomDatabaseHelper();
        
        public ConfigurationType(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public ConfigurationType()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {

            DTO.ConfigurationType dto;
                using(reader)
                {

                while(reader.Read())
                {
                    dto = new DTO.ConfigurationType();
                    dto.ConfigurationTypeDescription = 
                    _baseDatabase.resolveNullChar(reader.GetOrdinal("ConfigurationTypeDescription"), reader);
                    dto.ConfigurationTypeID = 
                    _baseDatabase.resolveNullInt32(reader.GetOrdinal("ConfigurationTypeID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
