//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNancy.Rules.RuleSet.DataAccess.DTO.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;
    
    
    public class RuleStatistic : List<DotNetNancy.Rules.RuleSet.DataAccess.DTO.RuleStatistic>
    {
        
        private CustomDatabaseHelper _baseDatabase = new CustomDatabaseHelper();
        
        public RuleStatistic(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public RuleStatistic()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {
        
            DotNetNancy.Rules.RuleSet.DataAccess.DTO.RuleStatistic dto;
                using(reader)
                {

                while(reader.Read())
                {
            dto = new DotNetNancy.Rules.RuleSet.DataAccess.DTO.RuleStatistic();
                    dto.RuleName = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("RuleName"), reader);
                    dto.ReferenceID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("ReferenceID"), reader);
                    dto.Result = 
                    _baseDatabase.resolveNullBoolean(reader.GetOrdinal("Result"), reader);
                    dto.RuleStatisticID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("RuleStatisticID"), reader);
                    dto.ApplicationID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("ApplicationID"), reader);
                    dto.TypeID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("TypeID"), reader);
                    dto.RuleID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("RuleID"), reader);
                    dto.DateInserted = 
                    _baseDatabase.resolveNullDateTime(reader.GetOrdinal("DateInserted"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
