//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNancy.Rules.RuleSet.DataAccess.DTO.List
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Text;


    public class Type : List<DTO.Type>
    {
        
        private CustomDatabaseHelper _baseDatabase = new CustomDatabaseHelper();
        
        public Type(System.Data.SqlClient.SqlDataReader reader)
        {
            this.AddItemsToListBySqlDataReader(reader);
        }
        
        public Type()
        {
        }
        
        public virtual void AddItemsToListBySqlDataReader(System.Data.SqlClient.SqlDataReader reader)
        {

            DTO.Type dto;
                using(reader)
                {

                while(reader.Read())
                {
                    dto = new DTO.Type();
                    dto.TypeFullName = 
                    _baseDatabase.resolveNullString(reader.GetOrdinal("TypeFullName"), reader);
                    dto.TypeID = 
                    _baseDatabase.retrieveGuidFromDataReader(reader.GetOrdinal("TypeID"), reader);
                    this.Add(dto);
                }

                }

        }
    }
}
